config/routes.rb
Madmin::Engine.routes.draw do
  root to: "dashboard#index"

  get "/:resource", to: "resources#index", as: :resources
  get "/:resource/new", to: "resources#new", as: :new_resource
  post "/:resource", to: "resources#create"
  get "/:resource/:id", to: "resources#show", as: :resource
  get "/:resource/:id/edit", to: "resources#edit", as: :edit_resource
  patch  "/:resource/:id", to: "resources#update"
  delete "/:resource/:id", to: "resources#destroy"
end

app/models/madmin/application_record.rb
module Madmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/madmin/field/check_box.rb
module Madmin
  class Field
    class CheckBox < Madmin::Field
    end
  end
end

app/models/madmin/field/date_time.rb
module Madmin
  class Field
    class DateTime < Madmin::Field
    end
  end
end

app/models/madmin/field/email.rb
module Madmin
  class Field
    class Email < Madmin::Field
    end
  end
end

app/models/madmin/field/number.rb
module Madmin
  class Field
    class Number < Madmin::Field
    end
  end
end

app/models/madmin/field/password.rb
module Madmin
  class Field
    class Password < Madmin::Field
    end
  end
end

app/models/madmin/field/text.rb
module Madmin
  class Field
    class Text < Madmin::Field
    end
  end
end

app/models/madmin/field/text_area.rb
module Madmin
  class Field
    class TextArea < Madmin::Field
    end
  end
end

app/controllers/madmin/application_controller.rb
module Madmin
  class ApplicationController < BaseController
    protect_from_forgery with: :exception

    before_action :authenticate!

    private

    def authenticate!
      # redirect_to x_path unless current_user
      #
      # If using Devise, set this method to call:
      # authenticate_user!
    end
  end
end

app/controllers/madmin/base_controller.rb
require_dependency "madmin/resources"

module Madmin
  class BaseController < ActionController::Base
    before_action :validate_resources

    private

    # Taking a peek at all the resources will raise an error if one isn't found.
    # Let's inform the user if we can't find a resource no matter what page
    # they're on. This should fail to prevent surprises at run time.
    def validate_resources
      Madmin::Resources.all
    end
  end
end

app/controllers/madmin/dashboard_controller.rb
require_dependency "madmin/application_controller"

module Madmin
  class DashboardController < ApplicationController
    def index
    end
  end
end

app/controllers/madmin/resources_controller.rb
require_dependency "madmin/application_controller"

module Madmin
  class ResourcesController < ApplicationController
    include ActiveSupport::Inflector

    before_action :find_resource, only: [:show, :edit, :update, :destroy]

    helper_method :madmin_resource

    def index
      @scopes = madmin_resource.scopes
      @headers = madmin_resource.index_headers

      if params[:scope]&.to_sym&.in?(@scopes)
        begin
          @collection = resource.send(params[:scope])
        rescue ArgumentError
          raise ScopeWithArgumentsError, "The scope #{params[:scope.to_sym]} on #{resource.name} takes arguments, which are currently unsupported."
        end
      else
        @collection = resource.all
      end

      respond_to do |format|
        format.html
        format.json { render json: @collection.map { |c| {id: c.id, display_value: c.title} } }
      end
    end

    def show
    end

    def new
      @resource = ResourceDecorator.new(resource.new(resource_params))
    end

    def create
      @resource = ResourceDecorator.new(resource.new(resource_params))

      if @resource.save
        redirect_to resource_path(id: @resource.id)
      else
        render :new
      end
    end

    def edit
    end

    def update
      if @resource.update(resource_params)
        redirect_to resource_path(id: @resource.id)
      else
        render :edit
      end
    end

    def destroy
      if @resource.destroy
        redirect_to resources_path(params[:resource])
      else
        flash[:error] = "There was an issue deleting the record."
        redirect_to :back
      end
    end

    private

    def find_resource
      @resource ||= Madmin::ResourceDecorator.new(resource.find(params[:id]))
    end

    def form_keys
      madmin_resource.form_fields.map { |field| field.strong_params_keys }.flatten
    end

    def madmin_resource
      Object.const_get("::Madmin::Resources::#{resource_name}").new
    end

    def resource
      Object.const_get(resource_name)
    end

    def resource_name
      camelize(params[:resource].singularize)
    end

    def resource_params
      param_key = resource_name.downcase.to_sym
      return unless params.dig(param_key)

      params.require(param_key).permit(form_keys)
    end
  end
end

app/helpers/madmin/application_helper.rb
module Madmin
  module ApplicationHelper
    def available_resources
      @available_resources ||= Madmin::Resources.gather.map { |model| madmin_resource_for(model: model) }
    end

    def madmin_resource_for(model:)
      Object.const_get("::Madmin::Resources::#{model}").new
    end

    def pages
      Madmin::Pages.all
    end
  end
end

app/helpers/madmin/fields/polymorphic_helper.rb
module Madmin
  module Fields
    module PolymorphicHelper
      def polymorphic_models(type)
        all_resources = Madmin::Resources.all.map { |r| Madmin::ResourceDecorator.new(r) }

        polymorphic_resources = all_resources.select { |resource|
          associations = resource.model.reflect_on_all_associations
          associations.select { |a| a.options.dig(:as) === type }.any?
        }

        polymorphic_resources.map(&:model)
      end

      def polymorphic_options_for_selected_type(form:, field:)
        options_from_collection_for_select(
          form.object.send(field.polymorphic_type_param).constantize.send(field.polymorphic_scope),
          :id,
          field.polymorphic_display_value,
          form.object.send(field.polymorphic_id_param)
        )
      end
    end
  end
end

app/views/layouts/madmin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Madmin</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <%= stylesheet_link_tag "madmin/application", media: "all" %>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <%= render 'application/navigation' %>
      <div class="col-10 ml-sm-auto mt-4">
        <div class="container">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>

  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <%= javascript_include_tag "madmin/application" %>
</body>
</html>

app/views/madmin/dashboard/index.html.erb
<h1>Administration</h1>
<% available_resources.each do |type| %>
  <li>
    <%= link_to type.friendly_name.pluralize, resources_path(type.slug) %>
  </li>
<% end %>

app/views/madmin/fields/check_box/_form.html.erb
<div class="form-group form-check">
  <%= form.check_box field.key, class: "form-check-input" %>
  <%= form.label field.key, field.label, class: "form-check-label" %>
</div>

app/views/madmin/fields/check_box/_index.html.erb
<%= field.value_for(resource) %>

app/views/madmin/fields/check_box/_show.html.erb
<div class="row">
  <div class="col-3">
    <%= field.label %>
  </div>
  <div class="col-9">
    <%= field.value_for(resource) %>
  </div>
</div>

app/views/madmin/fields/has_many/_show.html.erb
<div class="mt-3">
  <div class="row">
    <div class="col">
      <h3><%= field.label %></h3>
      <%= link_to "Add", new_resource_path(field.association_slug, field.association_param => { field.association_foreign_key => resource.id }) %>
      <%=
        render "madmin/resources/index/content",
               headers: [],
               collection: field.value_for(resource),
               madmin_resource: madmin_resource_for(model: field.association_class),
               show_new_button: false
      %>
    </div>
  </div>
</div>

app/views/madmin/fields/has_one/_show.html.erb
<div class="mt-3">
  <div class="row">
    <div class="col">
      <h3><%= field.name %></h3>
      <% if !field.value %>
        <%= link_to "Add", new_resource_path(madmin_resource_for(model: field.foreign_class).slug, ActiveModel::Naming.param_key(field.foreign_class) => { field.foreign_key => field.resource.id }) %>
      <% else %>
        <%= render "madmin/resources/index/content", headers: [], collection: [Madmin::ResourceDecorator.new(field.value)], show_new_button: false %>
      <% end %>
    </div>
  </div>
</div>

app/views/madmin/fields/number/_form.html.erb
<div class="form-group">
  <%= form.label field.key, field.label %>
  <%= form.number_field field.key, class: "form-control" %>
</div>

app/views/madmin/fields/number/_index.html.erb
<%= link_to field.value_for(resource), resource_path(madmin_resource.slug, id: resource.id) %>

app/views/madmin/fields/number/_show.html.erb
<div class="row">
  <div class="col-3">
    <%= field.label %>
  </div>
  <div class="col-9">
    <%= field.value_for(resource) %>
  </div>
</div>

app/views/madmin/fields/password/_form.html.erb
<div class="form-group">
  <%= form.label field.key, field.label %>
  <%= form.password_field field.key, class: "form-control", autocomplete: false %>
</div>

app/views/madmin/fields/password/_index.html.erb
<%= 'Password Encrypted' if field.value %>

app/views/madmin/fields/password/_show.html.erb
<div class="row">
  <div class="col-3">
    <%= field.label %>
  </div>
  <div class="col-9">
    <%= 'Password Encrypted' if field.value_for(resource).present? %>
  </div>
</div>

app/views/madmin/fields/polymorphic/_form.html.erb
<div class="form-group">
  <%= form.label field.key %>
  <%=
    form.select field.polymorphic_type_param,
                polymorphic_models(field.key).map { |m| [m.name, m.name, { "data-slug" => madmin_resource_for(model: m).slug }] },
                { include_blank: true },
                id: field.polymorphic_type_param,
                class: "form-control"
  %>
  <% if field.polymorphic_relationship_exists?(form.object) %>
    <%=
      form.select field.polymorphic_id_param,
                  polymorphic_options_for_selected_type(form: form, field: field),
                  {},
                  id: field.polymorphic_id_param,
                  class: "form-control"
    %>
  <% else %>
    <%=
      form.select field.polymorphic_id_param,
                  [],
                  {},
                  id: field.polymorphic_id_param,
                  class: "d-none form-control"
    %>
  <% end %>
</div>

<script>
  window.polymorphicFields = window.polymorphicFields || [];
  window.polymorphicFields.push('<%= field.key %>')
</script>

app/views/madmin/fields/polymorphic/_index.html.erb
<%= link_to field.polymorphic_value_for(resource), resource_path(field.polymorphic_slug_for(resource), field.polymorphic_id_for(resource)) %>

app/views/madmin/fields/polymorphic/_show.html.erb
<div class="row">
  <div class="col-3">
    <%= field.label %>
  </div>
  <div class="col-9">
    <%=
      link_to field.polymorphic_value_for(resource),
              resource_path(
                field.polymorphic_slug_for(resource),
                field.polymorphic_id_for(resource)
              )
    %>
  </div>
</div>

app/views/madmin/fields/select/_form.html.erb
<div class="form-group">
  <%= form.label field.key, field.label %>
  <%= form.select field.key, field.select_options, {}, class: "form-control" %>
</div>

app/views/madmin/fields/select/_index.html.erb
<%= field.value %>

app/views/madmin/fields/select/_show.html.erb
<div class="row">
  <div class="col-3">
    <%= field.label %>
  </div>
  <div class="col-9">
    <%= field.value_for(resource) %>
  </div>
</div>

app/views/madmin/resources/index/_content.html.erb
<table class="table">
  <thead>
    <% headers.each do |header| %>
      <th><%= header %></th>
    <% end %>
  </thead>
  <% if collection.any? %>
    <% collection.each do |resource| %>
      <tr>
        <% madmin_resource.index_fields.each do |field| %>
          <td>
            <%=
              render "#{field.to_partial_path}/index",
                     field: field,
                     madmin_resource: madmin_resource,
                     resource: resource
            %>
          </td>
        <% end %>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td>No records found</td>
    </tr>
  <% end %>
</table>

<% if show_new_button %>
  <div class="mt-4">
    <%= link_to 'New', new_resource_path, class: "btn btn-primary" %>
  </div>
<% end %>